tgchannel:
  - https://t.me/vpnfail_v2ray
  - https://t.me/free4allVPN
  - https://t.me/PrivateVPNs
  - https://t.me/V2rayng_Fast
  - https://t.me/DirectVPN
  - https://t.me/ProxyFn
  - https://t.me/V2RayRootFree
  - https://t.me/shadowsockskeys
  -
#  - https://t.me/WFVPN
#  - https://t.me/ripaojiedian
  - https://t.me/SSRSUB
#  - https://t.me/FProxies
  - https://t.me/TGVPN777
  - https://t.me/v2queen
  #2025年6月23日 新增
  - https://t.me/ZDYZ2
  #- https://t.me/vpn880
#  - https://t.me/freeyule
#  - https://t.me/suyucom
  # 2024-03-01 新增
#  - https://t.me/ShareCentre
  #- https://t.me/onessr
  #- https://t.me/freeshadowsock
#  - https://t.me/changfengchannel
#  - https://t.me/Free166
  #- https://t.me/aiuvpn
  #- https://t.me/ltscxk
  #- https://t.me/bpjzx2
#  - https://t.me/xiaoxinv
  #- https://t.me/murandepindao
  - https://t.me/ShareCentrePro
#  - https://t.me/zyfxlnn
#  - https://t.me/juzibaipiao
  - https://t.me/freeVPNjd
   # 2024-03-01 新增
#  - https://t.me/v2raydailyupdate
#  - https://t.me/allv2board
  # 2024-02-29 新增
  #- https://t.me/jcvpn
  - https://t.me/wxdy666
  #下面是自己添加的 LRC
  #- https://t.me/sharingnode      #节点地址http://file.52nfw.cn/word/obtain.php?user=111111&id=1
  #- https://t.me/aifenxiang2020   #分享的是节点信息
  #- https://t.me/ssrList          #分享的是节点信息，https://fanqiangdang.com提供
  - https://t.me/mftizi           #分享的是节点信息
  #- https://t.me/vmess_tg         #有源，有节点
  - https://t.me/freev2rays       #分享的是节点信息
  #- https://t.me/v2list           #分享的是节点信息，https://fanqiangdang.com提供
  #下面是自己添加的，好像都是分享的节点信息，订阅源抓不到
#  - https://t.me/yaney_01
  - https://t.me/bamboo_vpn
#  - https://t.me/maxshare
#  - https://t.me/BmFt1
#  - https://t.me/fffffx2
  #- https://t.me/gulaiguq_baipiao2
#  - https://t.me/Jsnzk
#  - https://t.me/wbnet
  - https://t.me/go4sharing
  #- https://t.me/miaomua
  #- https://t.me/allporter
#  - https://t.me/freekankan
  #- https://t.me/baipiao01
#  - https://t.me/vpnhat
  - https://t.me/dingyue_Center
#  - https://t.me/kxswa
#  - https://t.me/hkaa0
#  - https://t.me/iosfulishare
  #- https://t.me/univstar
